<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <% if(session.getAttribute("name")!=null && session.getAttribute("name").equals(1)) {
    	out.print("<!DOCTYPE html>\r\n"
    			+ "<html lang=\"en\">\r\n"
    			+ "<head>\r\n"
    			+ "    <meta charset=\"UTF-8\">\r\n"
    			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
    			+ "    <title>Document</title>\r\n"
    			+ "    <style>\r\n"
    			+ "        *{\r\n"
    			+ "            margin: 0;\r\n"
    			+ "        }\r\n"
    			+ "        .box{\r\n"
    			+ "            /* margin-top: 100px; */\r\n"
    			+ "            padding-top: 10px;\r\n"
    			+ "            width: 100%;\r\n"
    			+ "            height: 60px;\r\n"
    			+ "            display: flex;\r\n"
    			+ "            background-color: black;\r\n"
    			+ "            justify-content: space-evenly;\r\n"
    			+ "            \r\n"
    			+ "        }\r\n"
    			+ "        .box a{\r\n"
    			+ "            /* position: relative; */\r\n"
    			+ "            color:white;\r\n"
    			+ "            text-decoration: none;\r\n"
    			+ "            padding: 0px 20px 10px 20px;\r\n"
    			+ "            font-size: 25px;\r\n"
    			+ "        }\r\n"
    			+ "        .box a:hover,.dropButton:hover .butMobile{\r\n"
    			+ "            background-color: greenyellow;\r\n"
    			+ "        }\r\n"
    			+ "        .box-login{\r\n"
    			+ "            float: right;\r\n"
    			+ "            margin-right: 20px;\r\n"
    			+ "        }\r\n"
    			+ "        .dropButton button{\r\n"
    			+ "            background-color: black;\r\n"
    			+ "            color: white;\r\n"
    			+ "            padding-bottom: 30px;\r\n"
    			+ "            font-size: 25px;\r\n"
    			+ "            border: none;\r\n"
    			+ "            outline: none;\r\n"
    			+ "        }\r\n"
    			+ "        .dropBox{\r\n"
    			+ "            display: none;\r\n"
    			+ "            position: absolute;\r\n"
    			+ "            /* margin-top: 1px; */\r\n"
    			+ "            background-color: whitesmoke;\r\n"
    			+ "            \r\n"
    			+ "        }\r\n"
    			+ "        .dropBox a{\r\n"
    			+ "            display: block;\r\n"
    			+ "            color: black;\r\n"
    			+ "            /* float: none; */\r\n"
    			+ "        }\r\n"
    			+ "        /* .butMobile:hover{\r\n"
    			+ "            background-color: greenyellow;\r\n"
    			+ "        } */\r\n"
    			+ "        .dropBox a:hover{\r\n"
    			+ "            background-color: bisque;\r\n"
    			+ "        }\r\n"
    			+ "        .dropButton:hover .dropBox {\r\n"
    			+ "            display: block;\r\n"
    			+ "        }\r\n"
    			+ "        .logo{\r\n"
    			+ "            width: 200px;\r\n"
    			+ "            height: 120px;\r\n"
    			+ "            background-image: url(\"./img/logo.jpg\");\r\n"
    			+ "            background-size: cover;\r\n"
    			+ "        }\r\n"
    			+ "        .content{\r\n"
    			+ "            width: 90%;\r\n"
    			+ "            height: 1000px;\r\n"
    			+ "            display: flex;\r\n"
    			+ "            background-color: antiquewhite;\r\n"
    			+ "            margin-left: 75px;\r\n"
    			+ "            justify-content: space-evenly;\r\n"
    			+ "            flex-wrap: wrap;\r\n"
    			+ "        }\r\n"
    			+ "        .product-1,.product-2 ,.product-3{\r\n"
    			+ "            margin-top: 20px;\r\n"
    			+ "            width: 400px;\r\n"
    			+ "            height: 400px;\r\n"
    			+ "            /* border: 2px red solid; */\r\n"
    			+ "            text-align: center;\r\n"
    			+ "            /* margin-left: 10px; */\r\n"
    			+ "            \r\n"
    			+ "        }\r\n"
    			+ "    </style>\r\n"
    			+ "</head>\r\n"
    			+ "<body>\r\n"
    			+ "    <header>\r\n"
    			+ "        <div class=\"logo\"></div>\r\n"
    			+ "        <div class=\"box\">\r\n"
    			+ "            <a href=\"#\">Home</a>\r\n"
    			+ "            <a href=\"#\">News</a>\r\n"
    			+ "            <div class=\"dropButton\">\r\n"
    			+ "                <button type=\"button\" class=\"butMobile\">Mobile</button>\r\n"
    			+ "                <div class=\"dropBox\">\r\n"
    			+ "                <a href=\"#\">Apple</a>\r\n"
    			+ "                <a href=\"./samsung.jsp?limit=0\">Samsung</a>\r\n"
    			+ "                <a href=\"#\">Nothing</a>\r\n"
    			+ "                <a href=\"#\">OnePlus</a>\r\n"
    			+ "                </div>\r\n"
    			+ "            </div>\r\n"
    			+ "            <a href=\"#\">About</a>\r\n"
    			+ "            <a href=\"./session.jsp\" class=\"box-login\">LogOut</a>\r\n"
    			+ "        </div>\r\n"
    			+ "    </header>\r\n"
    			+ "    <div class=\"content\">\r\n"
    			+ "        <div class=\"product-1\"><a href=\"\"><img src=\"./img/iphone14.jpg\" alt=\"\" style=\"max-width: 250px;\"></a><p>Phone: Iphone 14</p>\r\n"
    			+ "            <p>Price:59999</p>\r\n"
    			+ "            <p>feature: 32MP rear camera</p>\r\n"
    			+ "            <p>8 GB RAM</p>\r\n"
    			+ "        </div>\r\n"
    			+ "        <div class=\"product-2\"><a href=\"\"><img src=\"./img/samsungS23Ultra.jpg\" alt=\"\" style=\"max-width: 250px;\"></a><p>Phone: Iphone 14</p>\r\n"
    			+ "            <p>Price:124599</p>\r\n"
    			+ "            <p>feature: 200MP rear camera</p>\r\n"
    			+ "            <p>12 GB RAM</p>\r\n"
    			+ "        </div>\r\n"
    			+ "        <div class=\"product-3\"><a href=\"\"><img src=\"./img/nothingPhone2.jpg\" alt=\"\" style=\"max-width: 250px;\"></a><p>Phone: Iphone 14</p>\r\n"
    			+ "            <p>Price:42599</p>\r\n"
    			+ "            <p>feature: 32MP rear camera</p>\r\n"
    			+ "            <p>8 GB RAM</p>\r\n"
    			+ "        </div>\r\n"
    			+ "        <div class=\"product-1\"><a href=\"\"><img src=\"./img/samsungZFold4.jpg\" alt=\"\" style=\"max-width: 225px;\"></a><p>Phone: Iphone 14</p>\r\n"
    			+ "        <p>Price:87999</p>\r\n"
    			+ "        <p>feature: 100MP rear camera</p>\r\n"
    			+ "        <p>8 GB RAM</p>\r\n"
    			+ "        </div>\r\n"
    			+ "        <div class=\"product-1\"><a href=\"\"><img src=\"./img/oneplus12.jpg\" alt=\"\" style=\"max-width: 250px; \"></a><p>Phone: Iphone 14</p>\r\n"
    			+ "            <p>Price:84599</p>\r\n"
    			+ "            <p>feature: 100MP rear camera</p>\r\n"
    			+ "            <p>12 GB RAM</p>\r\n"
    			+ "            </div>\r\n"
    			+ "        <div class=\"product-1\"><a href=\"\"><img src=\"./img/oneplus10Pro.jpg\" alt=\"\" style=\"max-width: 250px;\"></a><p>Phone: Iphone 14</p>\r\n"
    			+ "        <p>Price:56999</p>\r\n"
    			+ "        <p>feature: 100MP rear camera</p>\r\n"
    			+ "        <p>8 GB RAM</p>\r\n"
    			+ "        </div>\r\n"
    			+ "        \r\n"
    			+ "    </div>\r\n"
    			+ "</body>\r\n"
    			+ "</html>");
    	
    }
    else{
    	out.print("not working");
    }%>
